"""Add image source tracking to products

Revision ID: b1e34347a2e7
Revises: 9e5eb6922d08
Create Date: 2025-11-15 16:42:16.083476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e34347a2e7'
down_revision = '9e5eb6922d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_image_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('latest_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('latest_image_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('latest_image_updated')
        batch_op.drop_column('latest_image_url')
        batch_op.drop_column('latest_image_source')

    # ### end Alembic commands ###
